import type { MobileWorkspaceGroup } from "./types";

export const MOCK_WORKSPACE_GROUPS: MobileWorkspaceGroup[] = [
	{
		id: "ai-tasks",
		label: "Proposed tasks",
		tone: "ai-tasks",
		rows: [],
	},
	{
		id: "pinned",
		label: "Pinned",
		tone: "pinned",
		rows: [
			{
				id: "ws-mobile-shell",
				title: "Mobile workspace shell",
				directoryName: "mobile-shell",
				repoId: "repo-helmor",
				repoName: "helmor",
				repoInitials: "HM",
				state: "ready",
				mode: "worktree",
				status: "in-progress",
				branch: "mobile-workspace-shell",
				activeSessionId: "session-mobile-shell",
				activeSessionTitle: "Refine mobile drawer architecture",
				activeSessionAgentType: "codex",
				activeSessionStatus: "idle",
				primarySessionId: "session-mobile-shell",
				primarySessionTitle: "Mobile drawer architecture",
				primarySessionAgentType: "codex",
				pinnedAt: "2026-05-24T09:10:00.000Z",
				sessionCount: 4,
				messageCount: 128,
				workspaceUnread: 2,
				unreadSessionCount: 1,
				hasUnread: true,
				updatedAt: "2026-05-24T10:35:00.000Z",
				summary:
					"Preparing the mobile shell around a workspace-first drawer while keeping the current iOS navigation behavior intact.",
			},
		],
	},
	{
		id: "chats",
		label: "Chats",
		tone: "chats",
		rows: [
			{
				id: "ws-product-planning",
				title: "Mobile product planning",
				directoryName: "2026-05-24-mobile-product-planning",
				state: "ready",
				mode: "chat",
				status: "in-progress",
				branch: null,
				activeSessionId: "session-product-planning",
				activeSessionTitle: "Define first mobile milestones",
				activeSessionAgentType: "claude",
				activeSessionStatus: "idle",
				primarySessionId: "session-product-planning",
				primarySessionTitle: "Mobile milestones",
				primarySessionAgentType: "claude",
				sessionCount: 1,
				messageCount: 46,
				workspaceUnread: 0,
				unreadSessionCount: 0,
				hasUnread: false,
				updatedAt: "2026-05-24T08:20:00.000Z",
				summary:
					"Loose planning notes for the mobile workspace flow before it is connected to live Helmor data.",
			},
		],
	},
	{
		id: "done",
		label: "Done",
		tone: "done",
		rows: [
			{
				id: "ws-theme-tokens",
				title: "Theme token mapping",
				directoryName: "theme-token-mapping",
				repoId: "repo-helmor",
				repoName: "helmor",
				repoInitials: "HM",
				state: "ready",
				mode: "worktree",
				status: "done",
				branch: "theme-token-mapping",
				activeSessionId: "session-theme",
				activeSessionTitle: "Review final token names",
				activeSessionAgentType: "codex",
				activeSessionStatus: "completed",
				primarySessionId: "session-theme",
				primarySessionTitle: "Theme token mapping",
				primarySessionAgentType: "codex",
				sessionCount: 3,
				messageCount: 87,
				workspaceUnread: 0,
				unreadSessionCount: 0,
				hasUnread: false,
				updatedAt: "2026-05-23T17:05:00.000Z",
				summary:
					"Desktop and mobile theme tokens are aligned enough for the next UI pass.",
			},
		],
	},
	{
		id: "review",
		label: "In review",
		tone: "review",
		rows: [
			{
				id: "ws-agent-streaming",
				title: "Agent streaming UI",
				directoryName: "agent-streaming-ui",
				repoId: "repo-helmor",
				repoName: "helmor",
				repoInitials: "HM",
				state: "ready",
				mode: "worktree",
				status: "review",
				branch: "agent-streaming-ui",
				activeSessionId: "session-streaming-polish",
				activeSessionTitle: "Polish streaming message transitions",
				activeSessionAgentType: "codex",
				activeSessionStatus: "idle",
				primarySessionId: "session-streaming-core",
				primarySessionTitle: "Streaming message rendering",
				primarySessionAgentType: "codex",
				sessionCount: 5,
				messageCount: 214,
				workspaceUnread: 3,
				unreadSessionCount: 2,
				hasUnread: true,
				updatedAt: "2026-05-22T21:44:00.000Z",
				summary:
					"Streaming UI changes are ready for review, with message rendering and scroll behavior already exercised.",
			},
		],
	},
	{
		id: "progress",
		label: "In progress",
		tone: "progress",
		rows: [
			{
				id: "ws-workspace-summary-api",
				title: "Workspace summary surface",
				directoryName: "workspace-summary-surface",
				repoId: "repo-helmor",
				repoName: "helmor",
				repoInitials: "HM",
				state: "setup_pending",
				mode: "local",
				status: "in-progress",
				branch: "main",
				activeSessionId: "session-summary",
				activeSessionTitle: "Sketch mobile summary fields",
				activeSessionAgentType: "claude",
				activeSessionStatus: "running",
				primarySessionId: "session-summary",
				primarySessionTitle: "Mobile summary fields",
				primarySessionAgentType: "claude",
				sessionCount: 2,
				messageCount: 64,
				workspaceUnread: 1,
				unreadSessionCount: 1,
				hasUnread: true,
				updatedAt: "2026-05-24T07:48:00.000Z",
				summary:
					"Defines the compact data that mobile should show before full session browsing is enabled.",
			},
		],
	},
	{
		id: "backlog",
		label: "Backlog",
		tone: "backlog",
		rows: [
			{
				id: "ws-offline-cache",
				title: "Offline workspace cache",
				directoryName: "offline-workspace-cache",
				repoId: "repo-helmor",
				repoName: "helmor",
				repoInitials: "HM",
				state: "ready",
				mode: "worktree",
				status: "backlog",
				branch: "offline-workspace-cache",
				activeSessionId: null,
				activeSessionTitle: null,
				activeSessionAgentType: null,
				activeSessionStatus: null,
				primarySessionId: null,
				primarySessionTitle: null,
				primarySessionAgentType: null,
				sessionCount: 0,
				messageCount: 0,
				workspaceUnread: 0,
				unreadSessionCount: 0,
				hasUnread: false,
				updatedAt: "2026-05-19T12:12:00.000Z",
				summary:
					"Placeholder workspace for deciding which data should be available immediately on mobile cold start.",
			},
		],
	},
	{
		id: "canceled",
		label: "Canceled",
		tone: "canceled",
		rows: [
			{
				id: "ws-old-navigation-spike",
				title: "Old navigation spike",
				directoryName: "old-navigation-spike",
				repoId: "repo-helmor",
				repoName: "helmor",
				repoInitials: "HM",
				state: "ready",
				mode: "worktree",
				status: "canceled",
				branch: "old-navigation-spike",
				activeSessionId: "session-old-nav",
				activeSessionTitle: "Archive unused navigator experiment",
				activeSessionAgentType: "codex",
				activeSessionStatus: "completed",
				primarySessionId: "session-old-nav",
				primarySessionTitle: "Navigator experiment",
				primarySessionAgentType: "codex",
				sessionCount: 1,
				messageCount: 22,
				workspaceUnread: 0,
				unreadSessionCount: 0,
				hasUnread: false,
				updatedAt: "2026-05-16T15:30:00.000Z",
				summary:
					"An earlier navigation experiment kept for history but no longer part of the active mobile direction.",
			},
		],
	},
	{
		id: "archived",
		label: "Archived",
		tone: "archived",
		rows: [
			{
				id: "ws-archived",
				title: "Archived workspace",
				directoryName: "archived-workspace",
				repoId: "repo-helmor",
				repoName: "helmor",
				repoInitials: "HM",
				state: "archived",
				mode: "worktree",
				status: "done",
				branch: "archived-workspace",
				activeSessionId: "session-archived",
				activeSessionTitle: "Archived session",
				activeSessionAgentType: "codex",
				activeSessionStatus: "completed",
				primarySessionId: "session-archived",
				primarySessionTitle: "Archived session",
				primarySessionAgentType: "codex",
				sessionCount: 1,
				messageCount: 18,
				workspaceUnread: 0,
				unreadSessionCount: 0,
				hasUnread: false,
				updatedAt: "2026-05-14T13:10:00.000Z",
				summary: "Archived workspace retained for mobile grouping coverage.",
			},
		],
	},
];
